name: Build And Deploy on Kubernets

on:
  pull_request:
    branches:
      - release/*
      - main
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - release/*
    paths-ignore:
      - 'README.md'

jobs:
  build-auth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'basingo-abcall'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Autenticar con Google Cloud usando la cuenta de servicio
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Authenticate to Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          cd microservices/auth
          docker build -t us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/auth:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/auth:latest

  build-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'basingo-abcall'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Autenticar con Google Cloud usando la cuenta de servicio
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Authenticate to Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          cd microservices/user
          docker build -t us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/user:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/user:latest

  build-issues-management:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'basingo-abcall'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Autenticar con Google Cloud usando la cuenta de servicio
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Authenticate to Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          cd microservices/issues_management
          docker build -t us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/issues-management:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/issues-management:latest

  build-email-daemon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'basingo-abcall'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Autenticar con Google Cloud usando la cuenta de servicio
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Authenticate to Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          cd microservices/email_daemon
          docker build -t us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/email-daemon:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/email-daemon:latest

  deployment-k8s:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    needs: [build-user, build-auth, build-issues-management, build-email-daemon]
    steps:

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'basingo-abcall'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Autenticar con Google Cloud usando la cuenta de servicio
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Authenticate to Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Configure kubectl
      - name: Set up kubectl
        run: |
          gcloud config set project basingo-abcall
          gcloud container clusters get-credentials basinglo-abcall-k8s --zone us-central1

      # Eliminar el despliegue anterior
      #- name: Delete previous deployment
      #  run: |
      #    kubectl delete -f deployment/services --ignore-not-found=true

      # Aplicar el archivo de configuración de Kubernetes
      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f deployment/services
