from enum import Enum


class UserStatus(Enum):
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    INACTIVE = "INACTIVE"


class UserRoles(Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    CLIENT = "CLIENT"
    AGENT = "AGENT"


class IssueType(Enum):
    REQUEST = "REQUEST"
    COMPLAINT = "COMPLAINT"
    CLAIM = "CLAIM"
    SUGGESTION = "SUGGESTION"
    PRAISE = "PRAISE"

    @classmethod
    def get_keywords(cls):
        return {
            cls.REQUEST: [
                r"\bsolicit[ao]?\b",
                r"\brequerimient[oa]\b",
                r"\bpetici[oó]n\b",
                r"\bpedido\b",
                r"\basistencia\b",
                r"\bsolicitando\b",
                r"\bnecesito\b",
                r"\bquiero\b",
                r"\bme gustaría\b",
                r"\bagradecería\b",
                r"\bsería posible\b",
                r"\bpodría\b",
                r"\bme ayudar[íi]a\b",
                r"\bsolicitud\b",
                r"\brequiere\b",
                r"\bexigir\b",
                r"\bbuscar\b",
                r"\bservicio\b",
                r"\bconsultar\b",
                r"\bbuscar\b",
                r"\brequerir\b",
                r"\bconsult[ae]r\b",
                r"\binteresado\b",
                r"\bpreguntar\b",
                r"\bpedir\b",
                r"\bsolicitar\b",
                r"\bacceso\b",
                r"\bauxilio\b",
                r"\bnecesitar\b",
                r"\bdisponibilidad\b",
                r"\bsolicitar ayuda\b",
                r"\bsolicit[ae]r información\b",
                r"\bquiere saber\b",
                r"\brequerir ayuda\b",
                r"\bconsultar información\b",
                r"\bdesear\b",
                r"\btrabajo\b",
                r"\bcolaborar\b",
                r"\bconfirmar\b",
                r"\bconsultar disponibilidad\b",
                r"\bsugerencia\b",
                r"\bconfirmar asistencia\b",
                r"\bnecesito información\b",
                r"\brealizar consulta\b",
                r"\bquiero saber\b",
                r"\bsolicitar soporte\b",
                r"\badquirir\b",
                r"\brecibir\b",
                r"\bconsiderar\b",
                r"\bdebería\b",
                r"\bpedir información\b",
            ],
            cls.COMPLAINT: [
                r"\bquej[ao]s?\b",
                r"\breclam[ao]s?\b",
                r"\binconformidad\b",
                r"\bproblema\b",
                r"\bdescontent[ao]\b",
                r"\binsatisfacci[oó]n\b",
                r"\bmal[ao]\b",
                r"\bdeficiencia\b",
                r"\bmalo\b",
                r"\bdefectuoso\b",
                r"\bfalla\b",
                r"\bdificultad\b",
                r"\bdecepcionado\b",
                r"\bfrustraci[oó]n\b",
                r"\bincumplimiento\b",
                r"\berror\b",
                r"\binsatisfacción\b",
                r"\binjusticia\b",
                r"\bproblema\b",
                r"\bfallo\b",
                r"\bdespiste\b",
                r"\bmuy mal\b",
                r"\bnunca más\b",
                r"\bimpresionado\b",
                r"\badversión\b",
                r"\bdefecto\b",
                r"\bfalta\b",
                r"\bincumplir\b",
                r"\bnecesita mejorar\b",
                r"\bnecesito quejarme\b",
                r"\bqueja sobre\b",
                r"\bproblemas con\b",
                r"\bqueja de servicio\b",
                r"\bfalta de atención\b",
                r"\badversión por\b",
                r"\bfallar\b",
                r"\berror en el servicio\b",
                r"\badversión al producto\b",
                r"\bno me gusta\b",
                r"\bmal servicio\b",
                r"\bnunca más vuelvo\b",
                r"\bqueja por retraso\b",
                r"\badversión por calidad\b",
                r"\bqueja constante\b",
                r"\bmal trato\b",
                r"\bno me atendieron\b",
                r"\bno resolvieron\b",
            ],
            cls.CLAIM: [
                r"\bcompensaci[oó]n\b",
                r"\bresarcimiento\b",
                r"\bindemnizaci[oó]n\b",
                r"\breclamaci[oó]n\b",
                r"\bsolicito\b",
                r"\bexigiendo\b",
                r"\bcompensar\b",
                r"\bdevoluci[oó]n\b",
                r"\bresarcir\b",
                r"\breparaci[oó]n\b",
                r"\bgarantía\b",
                r"\brecuperaci[oó]n\b",
                r"\brembolso\b",
                r"\bdaños\b",
                r"\bperjuicio\b",
                r"\breclamando\b",
                r"\breparar\b",
                r"\bconseguir\b",
                r"\brestituir\b",
                r"\bdetallar\b",
                r"\badministrar\b",
                r"\bperdida\b",
                r"\breparaciones\b",
                r"\bdañ[oó]s\b",
                r"\breclamar\b",
                r"\bdemandar\b",
                r"\badjudicar\b",
                r"\bcompensar\b",
                r"\bsolicitar compensación\b",
                r"\bexigir indemnización\b",
                r"\bsolicitar reparación\b",
                r"\bsolicitar devolución\b",
                r"\bsolicitar garantía\b",
                r"\bresarcir\b",
                r"\brecuperar\b",
                r"\bdemanda\b",
                r"\bresolver daños\b",
                r"\bperjuicio económico\b",
                r"\bdemandar por\b",
                r"\bexigir compensación\b",
                r"\bdevolver producto\b",
                r"\bpedir indemnización\b",
                r"\bsolicitar reembolso\b",
                r"\bgarantizar\b",
                r"\bdemandar reparaciones\b",
                r"\breclamar compensación\b",
                r"\bexigir reparación\b",
                r"\bjusticia\b",
            ],
            cls.SUGGESTION: [
                r"\bsugerencia\b",
                r"\bidea\b",
                r"\bpropuesta\b",
                r"\brecomendaci[oó]n\b",
                r"\bmejorar\b",
                r"\binnovaci[oó]n\b",
                r"\bsugerir\b",
                r"\bproponer\b",
                r"\boptimizar\b",
                r"\bmodificar\b",
                r"\badaptar\b",
                r"\brenovar\b",
                r"\bperfeccionar\b",
                r"\bampliar\b",
                r"\breforzar\b",
                r"\bajustar\b",
                r"\bcambiar\b",
                r"\bmejor[ae]r\b",
                r"\bcrear\b",
                r"\bmodificar\b",
                r"\breestructurar\b",
                r"\borganizar\b",
                r"\bplanificar\b",
                r"\bconsiderar\b",
                r"\boptimizar\b",
                r"\bproponer\b",
                r"\bmejoramiento\b",
                r"\bsugerencia de mejora\b",
                r"\bcreatividad\b",
                r"\bbuscar soluciones\b",
                r"\binnovar\b",
                r"\bmejorar calidad\b",
                r"\bopciones\b",
                r"\badaptar proceso\b",
                r"\bconsultar opciones\b",
                r"\bactualizar\b",
                r"\bintegrar\b",
                r"\bsoluciones\b",
                r"\badaptar solución\b",
                r"\bprogreso\b",
                r"\bajustes\b",
                r"\bmejorar eficiencia\b",
                r"\bcambiar proceso\b",
                r"\bsimplificar\b",
                r"\boptimizar servicio\b",
                r"\bmejorar herramientas\b",
                r"\bresolver dificultad\b",
                r"\bpropuesta de mejora\b",
                r"\bmejorar funcionamiento\b",
                r"\bsimplificar proceso\b",
            ],
            cls.PRAISE: [
                r"\bfelicitaci[oó]n\b",
                r"\bfelicitaciones\b",
                r"\bagradecimiento\b",
                r"\bexcelente\b",
                r"\bfelicitar\b",
                r"\bbuena\b",
                r"\bmaravilloso\b",
                r"\bespectacular\b",
                r"\bperfecto\b",
                r"\bgenial\b",
                r"\bmuy bueno\b",
                r"\bincre[ií]ble\b",
                r"\bmuy satisfecho\b",
                r"\bme encanta\b",
                r"\bencantado\b",
                r"\bfabuloso\b",
                r"\bbrillante\b",
                r"\bmuy feliz\b",
                r"\badoro\b",
                r"\bmagnífico\b",
                r"\bexcelente servicio\b",
                r"\bgusto\b",
                r"\bexitoso\b",
                r"\bamable\b",
                r"\bproductivo\b",
                r"\bsatisfactorio\b",
                r"\bgran trabajo\b",
                r"\bagradable\b",
                r"\bfantástico\b",
                r"\bme gusta mucho\b",
                r"\bfeliz\b",
                r"\bsolución satisfactoria\b",
                r"\bagradecer\b",
                r"\bexitoso\b",
                r"\bgeneroso\b",
                r"\bcomprometido\b",
                r"\bmuy profesional\b",
                r"\bformidable\b",
                r"\bser excelente\b",
                r"\bagradezco\b",
                r"\bmuy bien hecho\b",
                r"\bme encanta el servicio\b",
                r"\bgran esfuerzo\b",
                r"\bmuy bien ejecutado\b",
                r"\bmaravillosa experiencia\b",
                r"\bmaravilloso servicio\b",
            ],
        }
